version: "2"
prepare:
  fetch:
    - url: https://raw.githubusercontent.com/rggen/rggen-devtools/master/config/rubocop_common.yml
      path: rubocop_common.yml
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-39-0
exclude_patterns:
  - "spec/"
