<% if Gem::Specification.find_all_by_name('rggen-devtools').empty? %>
inherit_from:
  - https://raw.githubusercontent.com/rggen/rggen-devtools/master/config/rubocop_common.yml
  - .rubocop_todo.yml
<% else %>
inherit_gem:
  rggen-devtools: config/rubocop_common.yml

inherit_from:
  - .rubocop_todo.yml
<% end %>
